version: '3.0'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=sa-east-1
      - SERVICES=dynamodb,sqs
    volumes:
      - ./script:/script
    ports:
      - '4566:4566'